baseURL = ""
languageCode = "en-us"
title = "Henrik Fogelberg"
theme = "resume"

[params]
    firstName = "Henrik"
    lastName = "Fogelberg"
    address = "Malmö, Sweden"
    contactNote = "Full stack developer"
    profileImage = "img/logo.svg"
    email = "henrik.fogelberg@gmail.com"
    description = "Full stack (mostly back end) developer. Fan of Golang. I work at a startup which makes it possibly to have creative, troll free and hateless discussions in digital media ."
    favicon = "img/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = true
    showExperience = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/henrikfogelberg/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/hfogelberg/"


[[params.handles]]
    name = "Slack"
    link = "https://ifragasatt.slack.com/messages/DANDMMUK1"
    icon = "slack"

[[params.handles]]
    name = "twitter"
    link = "https://twitter.com/hfogelberg"
    icon = "twitter"

[params.google.analytics]
    trackerID = "UA-107607086-01"

[context.production.environment]
  HUGO_VERSION = "0.47"