title = "Henrik Fogelberg"
baseURL = ""
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-107607086-1"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
publishDir = "henrik"

[Params]
    tagline = "Henrik Fogelberg"
    author = "Henrik Fogelberg"
    description = "Full stack web developer, based in Tenerife. Specialized in Golang and Vue."
    logoBig = "spiral.svg"
    logoSmall = "spiral.svg"
    favicon = "favicon.ico"
    opengraphImage = "profile.jpg"
    twitter = "hfogelberg"
    linkedin = "henrikfogelberg"
    github = "hfogelberg"
    email = "henrik.fogelberg@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4